site_name: e2s Viz

theme:
  name: material
  palette:
    primary: cyan
    accent: purple
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
- search
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    custom_templates: templates
    default_handler: python
    handlers:
      python:
        options:
          show_source: false



markdown_extensions:
  - codehilite:
      linenums: true
