site_name: e2s Viz

theme:
  name: material
  palette:
    primary: cyan
    accent: purple
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

plugins:
- search
- mkdocstrings

markdown_extensions:
  - codehilite:
      linenums: true
