class DateTimeSchema:
  HOUR = 'Hour'
  MINUTES = 'Minutes'
  SECONDS = 'Seconds'
  MONTH = 'Month'
  DAYOFWEEK = 'Day of week'
  WEEKDAYFLAG = 'Weekday flag'
  YEAR = 'Year'
  HALFHOUR = 'Half-hour'
  DATE = 'Date'
  WEEK = 'Week'
  DAYOFYEAR = 'Day of year'
  DATETIME = 'Datetime'
  TIME = 'time'
  WEEKEND = 'weekend'
  SEASON = 'season'
  SEASON_NUM = 'season_number'
